robotology/walking-controllers

- app/robots/iCubGazeboV2_5/dcm_walking/hand_retargeting/handRetargeting.ini
- app/robots/iCubGazeboV2_5/dcm_walking_retargeting.ini
- app/robots/iCubGenova04/dcm_walking/hand_retargeting/qpInverseKinematics.ini
- modules/Walking_module/src/WalkingModule.cpp
- modules/Walking_module/src/WalkingQPInverseKinematics.cpp
This PR:
* fixes a bug related to the resetting of the `m_retargetingClient`  e238df4
* fixes the configuration files for `iCubGenova04` and `iCubGazeboV2_5`
> Fix the bug related to the resetting of the hand retargeting client 

- src/WholeBodyControllers/src/QPInverseKinematics.cpp
I am currently having this error when compiling both on ``master`` and ``devel``:
```
/home/sdafarra/Software/robotology-superbuild/robotology/walking-controllers/src/WholeBodyControllers/src/QPInverseKinematics.cpp: In member function ‘void WalkingControllers::WalkingQPIK::evaluateHessianMatrix()’:
/home/sdafarra/Software/robotology-superbuild/robotology/walking-controllers/src/WholeBodyControllers/src/QPInverseKinematics.cpp:515:13: error: no match for ‘operator+’ (operand types are ‘Eigen::Map<Eigen::SparseMatrix<double, 0> >’ and ‘const Eigen::Product<Eigen::Product<Eigen::Transpose<Eigen::Map<Eigen::Matrix<double, -1, -1, 1> > >, Eigen::DiagonalWrapper<const Eigen::Map<const Eigen::Matrix<double, -1, 1> > >, 1>, Eigen::Map<Eigen::Matrix<double, -1, -1, 1> >, 0>’)
+ …
```
> Avoid error on missing operator+ when summing hessian components.

- modules/Walking_module/CMakeLists.txt
- modules/Walking_module/include/eigen_workaround/SparseCwiseUnaryOp.h
- modules/Walking_module/src/WalkingQPInverseKinematics.cpp
This commit adds a workaround for issue https://github.com/robotology/walking-controllers/issues/47 .
In particular, it adds a vendored SparseCwiseUnaryOp.h file that has the correctly marked protected
members, via a backport of https://gitlab.com/libeigen/eigen/-/commit/f59bed7a133322955dac03f3654def706aff3ba6 .
As the include guards of the vendored SparseCwiseUnaryOp.h are the same of the one contained in Eigen, by including it first in the compilation unit that have this problem, we are able to make sure that the Eigen's version is ignored.
The workaround is used only if the compiler is `MSVC` and for Eigen 3.3, as the issue is expected to be solved in Eigen 3.4, and especially because the `SparseCwiseUnaryOp.h` will probably be quite different in Eigen 3.4, and so  it is possible that …
> Add workaround for issue with MSVC 2019 and Eigen 3.3

- src/TrajectoryPlanner/src/TrajectoryGenerator.cpp
- src/WalkingModule/app/robots/iCubGazeboV2_5/dcm_walking/common/plannerParams.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking/hand_retargeting/plannerParams.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking/joypad_control/plannerParams.ini
- src/WalkingModule/app/robots/icubGazeboSim/dcm_walking/common/plannerParams.ini
This feature was implemented in the unicycle planner in https://github.com/robotology/unicycle-footstep-planner/pull/28. With this PR it is now possible to change the DCM offset for the last step, and as a consequence improve the robustness of the walking
> Add the possibility to set the last step dcm offset

- CHANGELOG.md
- CMakeLists.txt
- src/TimeProfiler/src/TimeProfiler.cpp
Related to https://github.com/robotology/robotology-superbuild/issues/366#issuecomment-600107376 and https://github.com/robotology/walking-controllers/issues/58#issuecomment-600107149
> Fix missing include in TimeProfiler.cpp

- src/WalkingModule/app/robots/iCubGenova04/dcm_walking/joypad_control/plannerParams.ini
To reduce vibrations while walking.
> Copied the parameters of hand_retargeting in joypad_control 

- src/TrajectoryPlanner/src/TrajectoryGenerator.cpp
- src/WalkingModule/src/Module.cpp
This PR should fix the stance phase machinery in the walking module.  In theory, the PR fixes https://github.com/robotology/walking-controllers/issues/66
- https://github.com/robotology/walking-controllers/commit/aa03967036475e705f2afa3e4b1d4a32d843ee6d fixes the bug spot by @S-Dafarra in https://github.com/robotology/walking-controllers/issues/66#issuecomment-683747596
- https://github.com/robotology/walking-controllers/commit/578f87da62c0a0be2efbcef118366a6b781a428d advances the `m_isStancePhase` trajectory as described in https://github.com/robotology/walking-controllers/issues/66#issuecomment-694719465
**Note:** before merging it should be tested on iCub
> Fix the stance phase machinery 

- CHANGELOG.md
- src/RetargetingHelper/src/Helper.cpp
This PR fixes a bug in the`RetargetingClient` class. In detail, the hand `transform` in the retargeting client is expressed with respect to the head frame.
> Bugfix in the retargeting client class

- CHANGELOG.md
- CMakeLists.txt
- src/SimplifiedModelControllers/CMakeLists.txt
`SimplifiedModelControllers` is using `iCub::ctrl::Integrator::Integrator`, but is not linking to `ctrlLib` from the `ICUB` CMake project. Before iDynTree 3 this was working thank to some lucky transitive linking, but to avoid problems it is better to link ctrlLib explicitly.
> Fix missing ctrlLib link in SimplifiedModelControllers

- CHANGELOG.md
- src/RobotInterface/CMakeLists.txt
- src/WalkingModule/CMakeLists.txt
* `WalkingControllersRobotInterface` uses ctrlLib in https://github.com/robotology/walking-controllers/blob/v0.4.0/src/RobotInterface/include/WalkingControllers/RobotInterface/Helper.h#L27 
* `WalkingModule` uses ctrlLib in https://github.com/robotology/walking-controllers/blob/44d2d4c0f8ff63ee689be7559cee6fd01e86ddd1/src/WalkingModule/include/WalkingControllers/WalkingModule/Module.h#L51
> Adding more missing link to ctrlLib

- CHANGELOG.md
- src/SimplifiedModelControllers/include/WalkingControllers/SimplifiedModelControllers/ZMPController.h
> Add include Position.h

- CHANGELOG.md
- src/WholeBodyControllers/CMakeLists.txt
Fix Eigen include error:
```
In file included from /home/valentino/work/robotology-superbuild/robotology/walking-controllers/src/WholeBodyControllers/src/InverseKinematics.cpp:21:0:
/home/valentino/work/robotology-superbuild/build/install/include/iDynTree/Core/EigenHelpers.h:16:10: fatal error: Eigen/Dense: No such file or directory
#include <Eigen/Dense>
^~~~~~~~~~~~~
compilation terminated.
```
cc @CarlottaSartore
> Add Eigen3 link library in WholeBodyControllers component

- cmake/WalkingControllersFindDependencies.cmake
This needs https://github.com/robotology/unicycle-footstep-planner/pull/47 to be merged first
> Bumped UnicyclePlanner required version.

- README.md
A dependency on blf was added in https://github.com/robotology/walking-controllers/pull/97 but was not documented in the README.
> Add blf dependency in README

- src/WalkingModule/app/robots/iCubGazeboV3/dcm_walking_with_joypad.ini
Currently in the installed `iCubGazeboV3` configuration the option `dump_data` set to true. This means that for running the `WalkingModule`, it is required to have the [`bipedal-locomotion-framework`](https://github.com/ami-iit/bipedal-locomotion-framework) logger module running.
In order to simplify the usage of such application, and make it compatible with the instruction in https://github.com/robotology/walking-controllers#computer-how-to-run-the-simulation, I am changing the default value to false.
> Remove logger from iCubGazeboV3 configuration

- cmake/WalkingControllersFindDependencies.cmake
- src/TrajectoryPlanner/src/TrajectoryGenerator.cpp
- src/WalkingModule/app/robots/iCubGenova09/dcm_walking/common/plannerParams.ini
This requires https://github.com/robotology/unicycle-footstep-planner/pull/53
> Enable the minimum jerk trajectory for the DCM first DS phase

- CMakeLists.txt
This fixes a compilation problem on Windows relative to the use of ``std::min``.
> Added some defines for the Windows case.

- src/WalkingModule/src/Module.cpp
This goes in the direction to reduce the pollution of the terminal while the application runs
> Print the timers status every 10 seconds

- src/RetargetingHelper/include/WalkingControllers/RetargetingHelper/Helper.h
The header seems not be used, and a leftover from https://github.com/robotology/walking-controllers/pull/118 .
Fix https://github.com/robotology/robotology-superbuild/issues/1269 .
> RetargetingHelper: Remove spurious blf include

- cmake/AddUninstallTarget.cmake
The one vendored in the repo is quite old.
> Update vendored AddUninstallTarget.cmake to YCM v0.15.1 version

- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/common/plannerParams.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/src/Module.cpp
This PR fixed a not initialized variable in the evaluation of the ZMP moreover it reduced the walking velocity of ergoCubSN000 and increase the planner_advance_time for iFeelWalking
> Fix not initialized variable in the evaluation of the measured ZMP and some tuning on ergoCubSN000 

- cmake/WalkingControllersDependencies.cmake
- src/WalkingModule/CMakeLists.txt
- src/WalkingModule/app/robots/ergoCubGazeboV1/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/ergoCubGazeboV1/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/app/robots/ergoCubGazeboV1/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/ergoCubGazeboV1_1/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/ergoCubGazeboV1_1/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/ergoCubSN001/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/ergoCubSN001/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/iCubGazeboV2_5/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/iCubGazeboV2_5/dcm_walking_joint_retargeting.ini
- src/WalkingModule/app/robots/iCubGazeboV2_5/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/iCubGazeboV3/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/iCubGazeboV3/dcm_walking_joint_retargeting.ini
- src/WalkingModule/app/robots/iCubGazeboV3/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking_with_joypad.ini
- src/WalkingModule/app/robots/iCubGenova09/dcm_walking/common/globalCoPEvaluator.ini
- src/WalkingModule/app/robots/iCubGenova09/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/app/robots/iCubGenova09/dcm_walking_with_joypad.ini
- src/WalkingModule/include/WalkingControllers/WalkingModule/Module.h
- src/WalkingModule/src/Module.cpp
With this PR `BipedalLocomotion::GlobalCoPEvaluator` is used to compute the global CoP for the walking controller. Thanks to this we centralize the code used to compute the quantity in all the projects
> Use BipedalLocomotion::GlobalCoPEvaluator to compute the global CoP

- src/WalkingModule/app/robots/ergoCubGazeboV1/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/ergoCubGazeboV1_1/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/ergoCubSN001/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/iCubGazeboV2_5/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/iCubGazeboV3/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/iCubGenova04/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/app/robots/iCubGenova09/dcm_walking/common/walkingLogger.ini
- src/WalkingModule/include/WalkingControllers/WalkingModule/Module.h
- src/WalkingModule/src/Module.cpp
This PR modifies the WalkingModule and the robot configuration files to be compliant with the YarpRobotLoggerMetadata introduced in https://github.com/ami-iit/bipedal-locomotion-framework/pull/767
> Enable the usage of VectorsCollectionMetadata in the WalkingModule

- README.md
The configuration files are save in the ``ICUBContrib`` folders. See https://github.com/robotology/walking-controllers/blob/56071b8ca640800667bb81b185c58307c7303ca7/src/WalkingModule/app/CMakeLists.txt#L45
> Fix YARP_DATA_DIRS and setGoal in readme

- src/TimeProfiler/include/WalkingControllers/TimeProfiler/TimeProfiler.h
- src/TimeProfiler/src/TimeProfiler.cpp
- src/WalkingModule/src/Module.cpp
@S-Dafarra modified the [TimeProfiler](https://github.com/robotology/walking-controllers/blob/56071b8ca640800667bb81b185c58307c7303ca7/src/TimeProfiler/src/TimeProfiler.cpp) to use the `std::chrono` to get the time. Moreover, he added a check on the time required to get the feedback in the [WalkingModule](https://github.com/robotology/walking-controllers/blob/56071b8ca640800667bb81b185c58307c7303ca7/src/WalkingModule/src/Module.cpp).
> Modify time profiler

- src/JoypadModule/app/dcmWalkingJoypad/joypad.ini
- src/JoypadModule/app/dcmWalkingJoypad/keyboard.ini
- src/JoypadModule/app/dcmWalkingJoypad/pedals.ini
- src/JoypadModule/include/WalkingControllers/JoypadModule/Module.h
- src/JoypadModule/src/Module.cpp
The pedals only provide 3 axis values and no buttons. I replicate the results obtained with TT robots on the main `WalkingJoypadModule`. In essence;
- To command the linear velocity, one needs to press both pedals equally.
- To command lateral Velocity, one needs to press one more than the other with the pressed one corresponding to the desired direction :warning: this also allows diagonal commands!
- To command the angular velocity one needs to push one pedals forward with the pushed pedal corresponding to the desired rotation direction
:warning: I need to test with the robot and also to check if I didn't break the other options (gamepad and keypoard). In theory It should be ok.
> Add `type` config option and possibility to use pedals

- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/autonomous/tasks/regularization.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/autonomous/tasks/retargeting.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/autonomous/tasks/torso.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/common/plannerParams.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/regularization.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/retargeting.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/iFeel_joint_retargeting/tasks/torso.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/joypad_control/tasks/regularization.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking/joypad_control/tasks/torso.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_autonomous.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_iFeel_joint_retargeting.ini
- src/WalkingModule/app/robots/ergoCubSN000/dcm_walking_with_joypad.ini
> Update frequency of the WalkingModule to 1 KHz for ergoCubSN000

- tests/CMakeLists.txt
I have installed the `robotology-superbuild` following [this readme](https://github.com/robotology/robotology-superbuild/blob/master/doc/conda-forge.md#source-installation).
Therefore, when installing the conda dependecies, I installed a recent version of CMake, which is `4.0.0`.
This cmake version, as per what stated in [the official documentation](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html), is no more compatible with cmake versions older than `3.5`:
> Changed in version 4.0: Compatibility with versions of CMake older than 3.5 is removed. Calls to [cmake_minimum_required(VERSION)](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) or [cmake_policy(VERSION)](https://cmake.org/cmake/help/latest/command/cmake_ …
> Bump minimum CMake version for tests to 3.10
